# Generated by Django 4.2.11 on 2024-06-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='rsbook_media')),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('1', 'Real Story Book'), ('2', 'Fiction Book')], max_length=1)),
                ('genre', models.CharField(choices=[('1', 'Comedy'), ('2', 'Action'), ('3', 'Crime'), ('4', 'Horror'), ('5', 'Romance'), ('6', 'Thriller'), ('7', 'Adventure'), ('8', 'Sports'), ('9', 'Inspirational')], max_length=1)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsbooks_app.rsauthor')),
            ],
        ),
    ]
